In [49]:
""" This notebook used for preporation data to NLP modeling.
 Proceses of Tokenization, Stemming, Lemmatization, Handling text (Remove HTML Tag, URLs, Emojies and other) are here.   """

import torch
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
import re                                              # Import Regular Expression (remove HTML tags)
import string                                          # Import Punctuation 
from textblob import TextBlob                          # Import this Library to Handle the Spelling Issue
import nltk
from nltk.corpus import stopwords                      #  NLTK library to remove Stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import emoji                                           # for translating symbol to text
import spacy                                           # for tokenization
import spacy.cli
# spacy.cli.download("en_core_web_sm")                 # for  working with spacy, after the first start should pick  # spacy.cli.download("en_core_web_lg")
from nltk.stem.porter import PorterStemmer             # for stemming
# nltk.download('all')                                   # for  working with NLTL function, after the first start should pick #nltk.download('all') 
from sklearn.model_selection import train_test_split
from chat_words import chat_word                       # for translate slang of charts to text
from autocorrect import Speller                        # for Spelling Correction
from collections import Counter, OrderedDict           # for definition of unique words (tokens) in dataframe
from torchtext.vocab import vocab  
from tqdm import tqdm                                   # progressbar
tqdm.pandas() 
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

In [50]:
df = pd.read_csv(r'C:\Users\Admin\WORK\Project_CV\Model_NLP_sentiment\data\IMDB Dataset.csv')    # insert path to your data

In [51]:
df.head(2)                                                # check dataframe

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [52]:
# transform sentiment  into the number labels
def transform_label(label):
    return 1 if label == 'positive' else 0

df['label'] = df['sentiment'].apply(transform_label)
df.head(2)

                                              review sentiment  label
0  One of the other reviewers has mentioned that ...  positive      1
1  A wonderful little production. <br /><br />The...  positive      1

In [53]:
# Choose items for preprocessing: True or False

lower = True                           # LoweCasing Text
remove_html = True                     # Remove HTML Tag
remove_url = True                       # Remove URLs
remove_punc = True                     # Remove punctuation
change_chat = True                     # Handling chat's words to words
spell_cor = True                       # Spelling Correction
remove_stopword = True                 # Remove StopWords
remove_emoji = True                  # Handling Emojies to words
use_stemm = False                       # Apply Stemming
use_lemm = True                        # Apply Lemmatization
use_token = False                       # Apply Tokenization

In [54]:
# Function for preprocessing
def preprocessing (text):
        
    if lower:                                                        # LoweCasing Text
        text = text.lower()
                                            
    if remove_html:
        pattern_1 = re.compile('<.*?>')                              # constant using one regular expression
        text = re.sub(pattern_1, r'', text)                          # Remove HTML Tags (changes ('<.*?>') to gap " ")

    if remove_url:
        pattern_2 = re.compile(r'https?://\S+|www\.\S+')             #  Remove URLs from Text or Whole Corpus.
        text = pattern_2.sub(r'', text)

    if remove_punc:
        punc = string.punctuation                                    # Remove punctuation
        text = text.translate(str.maketrans('', '', punc))

    if change_chat:
        new_text = []                                                 # changes chat's words to text       
        for i in text.split():
            if i.upper() in chat_word:
                new_text.append(chat_word[i.upper()])
            else:
                new_text.append(i)
        text = " ".join(new_text)
        new_text.clear()

    if spell_cor:
        spell = Speller(lang='en')                                    # Spelling Correction
        text = spell(text)

    if remove_stopword:
        stopword = stopwords.words('english')                          # Handling StopWords
        for word in text.split():
            if word in stopword:
                new_text.append('')
            else:
                new_text.append(word)
        pattern_3 = new_text[:]
        text = " ".join(pattern_3)

    if remove_emoji:
        text = emoji.demojize(text)                                   # Handling Emojies 

    
    if use_stemm:
        stemmer = PorterStemmer()                                     # Stemming
        text = " ".join([stemmer.stem(word)
                  for word in text.split()])
                            
        
    if use_lemm:
        lemmatizer = WordNetLemmatizer()                              #Lemmatization
        words = nltk.word_tokenize(text)
        lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
        text = ' '.join(lemmatized_words)


    if use_token:
        nlp = spacy.load('en_core_web_sm')                            # the English language model 'en_core_web_sm'
        text = nlp(text)                                              # cmd:  python -m spacy download en_core_web_sm

    return text

In [55]:
df_new = df.loc[0:130]

In [56]:
# # Applying function for preprocessing

# # X_trainn = X_train.apply(preprocessing)
# x_testt = x_test.apply(preprocessing)
# x_testt.head(2)

df_new['clean'] = df_new['review'].apply(preprocessing) 
df_new

C:\Users\Admin\AppData\Local\Temp\ipykernel_10020\145210384.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['clean'] = df_new['review'].apply(preprocessing)

,review,sentiment,label,clean
0,One of the other reviewers has mentioned that ...,positive,1,one reviewer mentioned watching 1 oz episode h...
1,A wonderful little production. <br /><br />The...,positive,1,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,1,thought wonderful way spend Tears eye hot summ...
3,Basically there's a family where a little boy ...,negative,0,basically there family little boy jake think t...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,better matter love Tears eye money visually st...
...,...,...,...,...
126,"""Revolt of the Zombies"" proves that having the...",negative,0,revolt zombie prof director revamp recycle ide...
127,"The complaints are valid, to me the biggest pr...",negative,0,complaint valid biggest problem soap opera aim...
128,This movie was one of the best movies that I h...,positive,1,movie one best movie seen year didnt see cameo...
129,I remember seeing this film in the mid 80's th...,positive,1,remember seeing film mid 80 thought well paced...
130,Two hours ago I was watching this brilliant mo...,positive,1,two hour ago watching brilliant movie overwhel...

In [57]:
 #get all processed reviews
reviews = df_new.clean.values
# merge into single variable, separated by whitespaces
words = ' '.join(reviews)
# obtain list of words
words = words.split()

# check our list
words[:10]

['one',
 'reviewer',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly']

In [58]:
print(len(words))

15280

In [59]:
# build vocabulary
counter = Counter(words)
vocab = sorted(counter, key=counter.get, reverse=True)
int2word = dict(enumerate(vocab, 1))
int2word[0] = '<PAD>'
word2int = {word: id for id, word in int2word.items()}

In [60]:

print(counter)
print(vocab)
print(int2word)
print(word2int)

Counter({'movie': 284, 'film': 218, 'one': 123, 'like': 98, 'story': 68, 'even': 67, 'good': 66, 'get': 65, 'scene': 63, 'see': 63, 'eye': 59, 'would': 55, 'character': 54, 'make': 53, 'man': 52, 'really': 50, 'much': 50, 'made': 45, 'never': 44, 'Tears': 44, 'bad': 44, 'well': 43, 'life': 43, 'way': 43, 'thing': 42, 'first': 41, 'seen': 41, 'could': 41, 'plot': 40, 'go': 39, 'also': 38, 'people': 37, 'actor': 36, 'many': 36, 'dont': 35, 'end': 34, 'say': 33, 'year': 33, 'know': 33, 'acting': 33, 'little': 32, 'still': 32, 'young': 32, 'find': 32, 'better': 31, 'best': 31, 'think': 30, 'star': 30, 'take': 30, 'show': 29, 'look': 29, 'lot': 29, 'going': 28, 'nothing': 28, 'old': 27, 'woman': 27, 'war': 27, 'want': 27, 'two': 27, 'pretty': 26, 'watch': 26, 'least': 25, 'ever': 24, 'got': 24, 'give': 24, 'love': 24, 'director': 24, 'work': 24, 'im': 24, 'three': 24, 'back': 23, 'cant': 23, 'worst': 23, 'something': 23, 'however': 23, 'right': 22, 'great': 22, 'performance': 22, 'didnt': 22, 'turn': 22, 'audience': 21, 'point': 21, 'u': 21, 'another': 21, 'actually': 21, 'thought': 20, 'try': 20, 'watching': 19, 'far': 19, 'around': 19, 'play': 19, 'ive': 19, 'new': 19, 'cast': 19, 'time': 19, 'role': 19, 'idea': 19, 'funny': 19, 'girl': 19, 'though': 19, 'house': 19, 'jimmy': 19, 'may': 18, 'come': 18, 'interesting': 18, 'friend': 18, 'kid': 18, 'sure': 18, 'need': 18, 'hard': 18, 'fan': 18, 'game': 18, 'true': 18, 'hollywood': 18, 'mario': 18, 'use': 17, 'doesnt': 17, 'whole': 17, 'there': 17, 'must': 17, 'real': 17, 'world': 17, 'quite': 17, 'men': 17, 'horror': 17, 'full': 17, 'police': 17, 'fact': 16, 'big': 16, 'last': 16, 'without': 16, 'book': 16, 'violence': 15, 'city': 15, 'home': 15, 'saw': 15, 'rather': 15, 'every': 15, 'matter': 15, 'black': 15, 'line': 15, 'let': 15, 'original': 15, 'bit': 15, 'anyone': 15, 'away': 14, 'piece': 14, 'comedy': 14, 'family': 14, '10': 14, 'making': 14, 'thats': 14, 'simply': 14, 'tell': 14, 'script': 14, 'father': 14, 'zombie': 13, 'seems': 13, 'success': 13, 'different': 13, 'meet': 13, 'place': 13, 'mother': 13, 'maybe': 13, 'effect': 13, 'example': 13, 'enough': 13, 'help': 13, 'part': 13, 'becomes': 13, 'course': 13, 'murder': 13, 'truly': 12, 'kane': 12, 'probably': 12, 'child': 12, 'nice': 12, 'looking': 12, 'played': 12, 'based': 12, 'everything': 12, 'interest': 12, 'since': 12, 'long': 12, 'trying': 12, 'keep': 12, 'sort': 12, 'feel': 12, 'version': 12, 'beginning': 12, 'dvd': 12, 'others': 12, 'isnt': 12, 'used': 12, 'put': 12, 'hand': 12, 'lead': 12, 'day': 12, 'sex': 11, 'death': 11, 'picture': 11, 'wonderful': 11, 'sense': 11, 'worth': 11, 'similar': 11, 'shot': 11, 'mr': 11, 'theme': 11, 'action': 11, 'taken': 11, 'bring': 11, 'believe': 11, 'almost': 11, 'actual': 11, 'usually': 11, 'later': 11, 'took': 11, 'killing': 11, 'half': 11, 'ten': 11, 'kind': 11, 'ridiculous': 11, 'top': 11, 'wait': 11, 'remember': 11, 'guy': 11, 'especially': 11, 'terrible': 11, 'actress': 11, 'job': 11, 'second': 11, 'small': 11, 'tom': 11, 'set': 10, 'classic': 10, 'given': 10, 'watched': 10, 'done': 10, 'killer': 10, 'instead': 10, 'human': 10, 'power': 10, 'dressed': 10, 'fun': 10, 'read': 10, 'awful': 10, 'lost': 10, 'type': 10, 'beautiful': 10, 'predictable': 10, 'feeling': 10, 'name': 10, 'he': 10, 'minute': 10, 'screen': 10, 'special': 10, 'someone': 10, 'cinema': 10, 'theyre': 10, 'although': 10, 'music': 10, 'heard': 10, 'stupid': 10, 'mind': 10, 'fall': 10, 'seem': 10, 'left': 10, 'upon': 10, 'number': 10, 'entertainment': 10, 'musical': 10, 'rose': 10, 'wife': 10, 'space': 10, 'hitchcock': 10, 'called': 9, 'face': 9, 'high': 9, 'lack': 9, 'experience': 9, 'become': 9, 'production': 9, 'voice': 9, 'dialogue': 9, '2': 9, 'wood': 9, 'thriller': 9, 'totally': 9, 'case': 9, 'rest': 9, 'boring': 9, 'series': 9, 'today': 9, 'white': 9, 'change': 9, 'writing': 9, 'might': 9, 'yes': 9, 'title': 9, 'attempt': 9, 'earlier': 9, 'enjoy': 9, 'dark': 9, 'sequel': 9, 'mountain': 9, 'cop': 9, 'twist': 9, 'novel': 9, 'yet': 9, 'completely': 9, 'obviously': 9, 'son': 9, 'art': 9, 'fred': 9, 'court': 9, 'word': 8, 'main': 8, 'due': 8, 'forget': 8, 'romance': 8, 'boy': 8, 'playing': 8, 'money': 8, 'next': 8, 'person': 8, 'direction': 8, 'cause': 8, 'despite': 8, 'slow': 8, 'planet': 8, 'came': 8, 'early': 8, 'apparently': 8, 'together': 8, 'evil': 8, 'involved': 8, 'excellent': 8, 'always': 8, 'hold': 8, 'wasnt': 8, 'fight': 8, 'king': 8, 'female': 8, 'john': 8, 'henry': 8, 'sequence': 8, 'absolutely': 8, 'anything': 8, 'several': 8, 'night': 8, 'genre': 8, 'else': 8, 'law': 8, 'begin': 8, 'short': 8, 'quality': 8, 'canton': 8, 'moment': 8, 'ending': 8, 'god': 8, 'getting': 8, 'seeing': 8, 'gore': 8, 'definitely': 8, 'crap': 8, 'rock': 8, 'davy': 8, 'japanese': 8, 'drug': 7, 'front': 7, 'nasty': 7, 'couldnt': 7, 'graphic': 7, 'kill': 7, 'entire': 7, 'terrific': 7, 'disappointed': 7, 'drama': 7, 'believable': 7, 'water': 7, 'adventure': 7, 'view': 7, 'entertaining': 7, 'soundtrack': 7, 'song': 7, 'liked': 7, 'care': 7, 'romantic': 7, 'along': 7, 'reminds': 7, 'write': 7, 'town': 7, 'horrible': 7, 'fine': 7, 'couple': 7, 'hour': 7, 'carry': 7, 'usual': 7, 'mean': 7, 'karen': 7, 'unfortunately': 7, 'behind': 7, 'seemed': 7, 'soon': 7, 'saving': 7, 'coming': 7, 'perhaps': 7, 'unique': 7, 'room': 7, 'finally': 7, 'pure': 7, 'told': 7, 'consequence': 7, 'trouble': 7, 'detail': 7, 'certainly': 7, 'okay': 7, 'hope': 7, 'american': 7, 'leader': 7, 'sound': 7, 'robespierre': 7, 'ii': 7, 'sir': 7, 'mentioned': 6, 'exactly': 6, 'cell': 6, 'italian': 6, 'wouldnt': 6, 'turned': 6, 'touch': 6, 'michael': 6, 'hot': 6, 'serial': 6, 'average': 6, 'parent': 6, 'previous': 6, 'brings': 6, 'sympathetic': 6, 'dated': 6, 'tv': 6, 'hero': 6, 'felt': 6, 'country': 6, 'less': 6, 'happy': 6, 'problem': 6, 'cheese': 6, 'scary': 6, 'cry': 6, 'secret': 6, 'island': 6, 'german': 6, 'spoiler': 6, 'reason': 6, 'stay': 6, 'cut': 6, 'thinking': 6, 'running': 6, 'except': 6, 'machine': 6, 'wanted': 6, 'final': 6, 'victim': 6, 'nominated': 6, 'wrong': 6, 'stop': 6, 'painful': 6, 'start': 6, 'worse': 6, 'unless': 6, 'talk': 6, 'guess': 6, 'open': 6, '4': 6, 'video': 6, 'entirely': 6, 'brought': 6, 'mostly': 6, 'land': 6, 'robert': 6, 'ryan': 6, 'thus': 6, 'news': 6, 'question': 6, 'indian': 6, 'officer': 6, 'anand': 6, 'memorable': 6, 'citta': 6, 'business': 6, 'element': 6, 'expect': 6, 'gave': 6, 'bored': 6, 'television': 6, 'throughout': 6, 'act': 6, 'gun': 6, 'killed': 6, 'army': 6, 'butcher': 6, 'began': 6, 'obvious': 6, 'whose': 6, 'stuff': 6, 'screenplay': 6, 'premise': 6, 'found': 6, 'body': 6, 'blood': 6, 'office': 6, 'often': 6, 'everyone': 6, 'hole': 6, 'crocodile': 6, 'rocky': 6, 'oz': 5, 'focus': 5, 'prison': 5, 'level': 5, 'street': 5, 'extremely': 5, 'written': 5, 'dream': 5, 'control': 5, 'style': 5, 'basically': 5, 'fighting': 5, 'decides': 5, 'youre': 5, 'ruin': 5, 'dialog': 5, 'offer': 5, 'york': 5, 'talented': 5, 'favorite': 5, 'paul': 5, 'dozen': 5, 'na': 5, '70': 5, 'brilliant': 5, 'lame': 5, 'cheap': 5, 'hell': 5, 'joke': 5, 'eventually': 5, 'brother': 5, 'daughter': 5, 'angle': 5, 'enjoyed': 5, 'bold': 5, 'bought': 5, 'warned': 5, 'carver': 5, 'looked': 5, 'beyond': 5, 'started': 5, 'can': 5, 'not': 5, 'laugh': 5, 'week': 5, 'annoying': 5, 'shoot': 5, 'train': 5, 'saying': 5, 'roll': 5, 'unbelievable': 5, 'school': 5, 'supposed': 5, 'relationship': 5, 'terror': 5, 'exception': 5, 'major': 5, 'thrill': 5, 'chance': 5, 'development': 5, 'please': 5, 'hear': 5, 'surprise': 5, 'plenty': 5, 'agent': 5, 'happen': 5, 'fake': 5, 'towards': 5, 'weird': 5, 'wont': 5, 'hilarious': 5, 'bunch': 5, 'run': 5, 'pick': 5, 'honestly': 5, 'fellow': 5, 'shes': 5, 'singer': 5, 'numerous': 5, 'follow': 5, 'inside': 5, 'brain': 5, 'turning': 5, 'spirit': 5, 'serious': 5, 'america': 5, 'cold': 5, 'battle': 5, 'soldier': 5, 'southern': 5, 'surprisingly': 5, 'ray': 5, 'past': 5, 'century': 5, 'vision': 5, 'suspense': 5, 'company': 5, 'happens': 5, 'close': 5, 'successful': 5, 'system': 5, 'crime': 5, 'among': 5, 'halfway': 5, 'di': 5, 'truth': 5, 'board': 5, 'release': 5, 'deep': 5, 'memory': 5, 'single': 5, 'five': 5, 'viewing': 5, 'humor': 5, 'suicide': 5, 'virgin': 5, 'struggle': 5, 'husband': 5, 'call': 5, 'shooting': 5, 'camera': 5, 'william': 5, 'lover': 5, 'heart': 5, 'hit': 5, 'highly': 5, 'mission': 5, 'gang': 5, 'car': 5, 'oldid': 5, 'public': 5, 'nearly': 5, 'citizen': 5, 'charles': 5, 'tracy': 5, 'union': 5, 'ton': 5, 'sally': 5, 'tragedy': 5, 'wealthy': 5, 'western': 5, 'narrative': 5, 'none': 5, 'french': 5, 'difficult': 5, 'viewer': 5, 'rape': 5, 'speech': 5, 'producer': 5, 'free': 5, 'norman': 5, 'cameo': 5, 'finned': 5, 'courtesy': 5, 'arent': 5, 'named': 5, 'silly': 5, 'creature': 5, 'otherwise': 5, 'golf': 5, 'surf': 5, 'weston': 5, '23': 5, 'difference': 5, 'castle': 5, 'polish': 5, '1': 4, 'punch': 4, 'state': 4, 'gangster': 4, 'skill': 4, 'side': 4, 'filming': 4, 'solid': 4, 'particularly': 4, 'flat': 4, 'sitting': 4, 'air': 4, 'theater': 4, 'realize': 4, 'match': 4, 'id': 4, 'laughed': 4, 'tone': 4, 'jake': 4, 'soap': 4, 'watchable': 4, 'situation': 4, 'present': 4, 'live': 4, 'stage': 4, 'loneliness': 4, 'steve': 4, 'alive': 4, '25': 4, 'lucas': 4, 'whats': 4, 'happening': 4, 'wan': 4, 'leave': 4, 'amazing': 4, 'complete': 4, 'waste': 4, 'band': 4, 'forward': 4, 'mistake': 4, 'storyline': 4, 'giving': 4, 'effort': 4, 'alien': 4, 'eating': 4, 'b': 4, 'monster': 4, 'loved': 4, 'ball': 4, 'jack': 4, 'scientist': 4, 'havent': 4, 'area': 4, 'tried': 4, 'fantastic': 4, 'famous': 4, 'george': 4, 'recommend': 4, 'intrigue': 4, 'pas': 4, 'million': 4, 'mile': 4, 'fails': 4, 'trade': 4, 'ghost': 4, 'return': 4, 'nazi': 4, 'either': 4, 'save': 4, '20': 4, 'sticker': 4, 'die': 4, 'box': 4, 'constantly': 4, 'surely': 4, 'london': 4, 'using': 4, 'needed': 4, 'expectation': 4, 'crappy': 4, 'appear': 4, 'costume': 4, 'barely': 4, '310': 4, 'originally': 4, 'known': 4, '90': 4, 'standard': 4, 'carpenter': 4, 'stronger': 4, 'imagination': 4, 'door': 4, 'target': 4, 'worked': 4, 'subject': 4, 'lie': 4, 'surprised': 4, 'oscar': 4, 'walk': 4, 'wonder': 4, 'member': 4, 'blockbuster': 4, 'poor': 4, 'stereotypical': 4, 'responsible': 4, 'mention': 4, 'starring': 4, 'glory': 4, 'period': 4, 'ada': 4, 'indeed': 4, 'impressive': 4, 'scenario': 4, 'wanting': 4, 'meanwhile': 4, 'unfolds': 4, 'changed': 4, 'message': 4, 'atmosphere': 4, 'neither': 4, 'altogether': 4, 'host': 4, 'detective': 4, 'who': 4, 'third': 4, 'superior': 4, 'draw': 4, 'dealt': 4, 'studio': 4, 'whether': 4, 'mumbai': 4, 'unlike': 4, 'within': 4, 'portraying': 4, 'revenge': 4, 'motion': 4, 'protagonist': 4, 'italy': 4, 'introduced': 4, 'living': 4, 'missing': 4, 'manager': 4, 'spectator': 4, 'showing': 4, 'le': 4, 'dellamore': 4, 'taking': 4, 'occasional': 4, 'tension': 4, 'language': 4, 'listen': 4, 'including': 4, 'double': 4, 'medium': 4, '80': 4, 'writer': 4, 'went': 4, 'james': 4, 'region': 4, 'gary': 4, 'trailer': 4, 'jeep': 4, 'held': 4, 'mormon': 4, 'event': 4, 'singing': 4, 'bigger': 4, 'talking': 4, 'thousand': 4, 'surge': 4, 'late': 4, 'imdb': 4, 'lane': 4, 'spencer': 4, 'bos': 4, 'shock': 4, 'kung': 4, 'martial': 4, 'minor': 4, 'slapstick': 4, 'familiar': 4, 'safety': 4, 'married': 4, 'knew': 4, 'trial': 4, 'affair': 4, 'added': 4, 'dead': 4, 'support': 4, 'aftermath': 4, 'execution': 4, 'create': 4, 'hill': 4, 'national': 4, 'leaf': 4, 'ring': 4, 'perfect': 4, 'moving': 4, 'villain': 4, 'putting': 4, 'convincing': 4, 'peter': 4, 'important': 4, 'comedic': 4, 'disappointing': 4, 'stephen': 4, 'remake': 4, 'torture': 4, 'typical': 4, 'gem': 4, 'lite': 4, 'easy': 4, 'franchise': 4, 'q': 4, 'muster': 4, 'bill': 4, 'comparison': 4, 'winning': 4, 'super': 4, 'station': 4, 'flick': 4, 'correct': 4, 'genius': 4, 'galaxy': 4, 'weak': 4, 'reach': 4, 'grudge': 4, 'glad': 4, 'barnes': 4, 'possibly': 4, 'outrageous': 4, 'peach': 4, 'browser': 4, 'bubble': 4, 'handsome': 4, 'row': 4, 'copy': 4, 'opposed': 4, 'wing': 4, 'episode': 3, 'metre': 3, 'struck': 3, 'pull': 3, 'maximum': 3, 'agenda': 3, 'irish': 3, 'dealing': 3, 'appeal': 3, 'ready': 3, 'developed': 3, 'taste': 3, 'guard': 3, 'middle': 3, 'darker': 3, 'technique': 3, 'assuming': 3, 'fashion': 3, 'sometimes': 3, 'realism': 3, 'editing': 3, 'master': 3, 'spend': 3, 'fully': 3, 'image': 3, 'wear': 3, 'suddenly': 3, 'stunning': 3, 'portrait': 3, 'relation': 3, 'telling': 3, 'connected': 3, 'sincere': 3, 'luck': 3, '15': 3, 'davis': 3, 'thumb': 3, 'pace': 3, 'fresh': 3, 'creator': 3, 'followed': 3, 'brilliance': 3, 'fit': 3, 'huge': 3, 'positive': 3, 'comment': 3, 'pacing': 3, 'rarely': 3, 'credit': 3, 'gut': 3, 'mom': 3, 'address': 3, 'odd': 3, 'low': 3, 'stone': 3, '12': 3, 'helpless': 3, 'tired': 3, 'formula': 3, 'included': 3, 'notice': 3, 'possible': 3, 'ago': 3, 'player': 3, 'schneider': 3, 'tier': 3, 'mad': 3, 'dr': 3, 'delivers': 3, 'shakespeare': 3, 'hence': 3, 'english': 3, 'constant': 3, 'amateur': 3, 'project': 3, 'stock': 3, 'bizarre': 3, 'nowhere': 3, 'absurd': 3, 'dance': 3, 'wasted': 3, 'spent': 3, 'older': 3, 'emotional': 3, 'matrix': 3, 'spider': 3, 'disappointment': 3, 'dad': 3, 'dy': 3, 'etc': 3, 'shame': 3, 'golden': 3, 'painter': 3, 'complaint': 3, 'sly': 3, 'expert': 3, 'undeniably': 3, 'buddy': 3, 'hal': 3, 'hurt': 3, 'whilst': 3, 'lower': 3, 'wearing': 3, 'aspect': 3, 'respectable': 3, 'amusing': 3, 'utterly': 3, 'straight': 3, 'speed': 3, 'godzilla': 3, 'addition': 3, 'vhs': 3, 'kept': 3, 'surviving': 3, 'season': 3, 'according': 3, 'scale': 3, 'amount': 3, 'complex': 3, 'accurate': 3, 'portrays': 3, 'dumb': 3, 'album': 3, 'rating': 3, 'masterpiece': 3, 'trip': 3, 'creating': 3, 'anywhere': 3, 'future': 3, 'hopefully': 3, 'failed': 3, 'physically': 3, 'presented': 3, 'journey': 3, 'haunted': 3, 'entity': 3, 'explanation': 3, 'venture': 3, 'onto': 3, 'noticed': 3, 'showed': 3, 'reality': 3, 'crazy': 3, 'list': 3, 'existence': 3, 'able': 3, 'stand': 3, 'speak': 3, 'madness': 3, 'dancing': 3, 'reached': 3, 'grain': 3, 'compelling': 3, 'nicole': 3, 'edward': 3, 'gruesome': 3, 'appears': 3, 'root': 3, 'somewhat': 3, 'confusing': 3, 'disturbing': 3, 'deeply': 3, 'affected': 3, 'nature': 3, 'bar': 3, 'drunk': 3, 'matchup': 3, 'male': 3, 'hate': 3, 'general': 3, 'finest': 3, 'directed': 3, 'leading': 3, 'practical': 3, 'approach': 3, 'describes': 3, 'desired': 3, 'anger': 3, 'aware': 3, 'practice': 3, 'influence': 3, 'cult': 3, 'print': 3, 'dull': 3, 'ultimately': 3, 'adding': 3, 'dubbed': 3, 'quote': 3, 'hotel': 3, 'employee': 3, 'bank': 3, 'count': 3, 'girolamos': 3, 'bluff': 3, 'accepted': 3, '50': 3, 'identity': 3, 'unexpectedly': 3, 'mobster': 3, 'explicit': 3, 'provide': 3, 'waiting': 3, 'produce': 3, 'build': 3, 'tedious': 3, 'fast': 3, 'seriously': 3, 'anyway': 3, 'talent': 3, 'avoid': 3, 'age': 3, 'rated': 3, 'rent': 3, 'portrayed': 3, 'teenager': 3, 'eleven': 3, 'created': 3, 'suggests': 3, 'following': 3, 'figure': 3, 'david': 3, 'greatest': 3, 'program': 3, 'thrown': 3, 'steal': 3, 'clearly': 3, 'shut': 3, 'creepy': 3, 'jr': 3, 'hong': 3, 'kong': 3, 'harbor': 3, 'w': 3, 'grace': 3, 'missionary': 3, 'contains': 3, 'sent': 3, 'figured': 3, 'grade': 3, 'compared': 3, 'easier': 3, 'opinion': 3, 'enjoyable': 3, 'supporting': 3, 'animal': 3, 'red': 3, 'garner': 3, 'thanks': 3, 'eve': 3, 'learns': 3, 'jump': 3, 'diablo': 3, 'wooden': 3, 'equivalent': 3, 'fest': 3, '3': 3, 'exploitation': 3, 'skilled': 3, 'temple': 3, 'learn': 3, 'move': 3, 'hospital': 3, 'fell': 3, 'already': 3, 'sentence': 3, 'beta': 3, 'appeared': 3, 'bride': 3, 'bush': 3, 'shown': 3, 'test': 3, 'lovely': 3, 'jaw': 3, 'documentary': 3, 'risen': 3, 'explains': 3, 'settled': 3, 'filme': 3, 'includes': 3, 'decent': 3, 'outside': 3, 'daniel': 3, 'returned': 3, 'knowing': 3, 'directing': 3, 'authority': 3, 'include': 3, 'martin': 3, 'terrorist': 3, 'afraid': 3, 'employer': 3, 'term': 3, 'longer': 3, 'phone': 3, 'favourite': 3, 'besides': 3, 'miller': 3, 'ok': 3, 'laughable': 3, 'fulfil': 3, 'investigation': 3, 'mystery': 3, 'share': 3, 'alexandra': 3, 'replacement': 3, 'capable': 3, 'jim': 3, 'unwatchable': 3, 'visual': 3, 'salman': 3, 'furthermore': 3, 'disaster': 3, 'latter': 3, 'aff': 3, 'across': 3, 'overall': 3, 'clear': 3, 'bull': 3, 'feature': 3, 'subtle': 3, 'ndor': 3, 'chick': 3, 'childhood': 3, '2000': 3, 'delightful': 3, 'ed': 3, 'modern': 3, 'border': 3, 'peace': 3, 'proud': 3, 'brutal': 3, 'andrew': 3, 'entail': 3, 'porno': 3, 'murderer': 3, 'revolutionary': 3, 'limited': 3, 'review': 3, 'doug': 3, 'record': 3, 'mike': 3, 'immediately': 3, 'rare': 3, 'intriguing': 3, 'universe': 3, 'swear': 3, 'psychic': 3, 'discovers': 3, 'oh': 3, 'accent': 3, 'stuck': 3, 'unforgettable': 3, 'steele': 3, 'said': 3, 'youve': 3, 'ill': 3, 'dean': 3, 'fuer': 3, 'brady': 3, 'friendship': 3, 'theatrical': 3, 'farce': 3, 'brown': 3, 'plain': 3, 'pet': 3, 'multiple': 3, 'remote': 3, 'van': 3, 'manson': 3, 'n': 3, 'f': 3, 'seventy': 3, 'blonde': 3, 'nut': 3, 'claim': 3, 'trek': 3, 'quinn': 3, 'paris': 3, 'committee': 3, 'matthew': 3, 'revert': 3, 'hooked': 2, 'happened': 2, 'trust': 2, 'regard': 2, 'security': 2, 'mainly': 2, 'muslim': 2, 'latino': 2, 'christian': 2, 'dodgy': 2, 'shady': 2, 'dare': 2, 'charm': 2, 'mess': 2, 'inmate': 2, 'class': 2, 'conforming': 2, 'pat': 2, 'reference': 2, 'masterful': 2, 'fantasy': 2, 'sens': 2, 'terribly': 2, 'simplistic': 2, 'witty': 2, 'proof': 2, 'allen': 2, 'scarlet': 2, 'johnson': 2, 'managed': 2, 'sexy': 2, 'closet': 2, 'opera': 2, 'ramo': 2, 'decide': 2, 'expected': 2, 'meaningless': 2, 'vivid': 2, 'encounter': 2, 'contact': 2, 'sophisticated': 2, 'adrian': 2, 'wish': 2, 'alltime': 2, 'sacrifice': 2, 'tear': 2, 'widget': 2, 'awakening': 2, 'shunt': 2, 'tech': 2, 'excitement': 2, 'vote': 2, 'sea': 2, 'thank': 2, 'plus': 2, 'doubt': 2, 'innovative': 2, '8': 2, 'dropped': 2, '1990': 2, 'anymore': 2, 'continued': 2, 'decline': 2, 'disgraceful': 2, 'painfully': 2, 'chose': 2, 'respect': 2, 'encouraged': 2, 'titel': 2, 'camp': 2, 'quirky': 2, 'humour': 2, 'budget': 2, 'imagine': 2, 'recall': 2, 'died': 2, 'sat': 2, 'screenwriter': 2, 'rule': 2, 'finished': 2, 'research': 2, 'til': 2, 'self': 2, 'tale': 2, 'hail': 2, 'bass': 2, 'kicking': 2, 'cemented': 2, 'gm': 2, 'tree': 2, 'rich': 2, 'gone': 2, 'shenanigan': 2, 'boat': 2, 'enters': 2, 'appreciate': 2, 'scottish': 2, 'certain': 2, 'everybody': 2, 'drawn': 2, 'lesson': 2, 'skin': 2, 'heterosexual': 2, 'aid': 2, 'capture': 2, 'wilson': 2, 'fault': 2, 'jackson': 2, 'busy': 2, 'blatantly': 2, 'stolen': 2, 'v': 2, 'juvenile': 2, 'conclusion': 2, 'adult': 2, 'sister': 2, 'neburg': 2, 'england': 2, 'tiger': 2, 'snow': 2, 'appearance': 2, 'grizzly': 2, 'dan': 2, 'renaissance': 2, 'recognition': 2, 'perfectly': 2, 'account': 2, 'artist': 2, '1990s': 2, 'rescue': 2, 'stallion': 2, 'facial': 2, 'excuse': 2, 'pile': 2, 'horse': 2, 'romp': 2, 'unintentionally': 2, 'speedy': 2, 'tick': 2, 'cringeworthy': 2, 'disbelief': 2, 'captor': 2, 'anybody': 2, 'ralph': 2, 'frank': 2, 'former': 2, 'burning': 2, 'copper': 2, 'shouldnt': 2, 'sprinkled': 2, 'regret': 2, 'grow': 2, 'anime': 2, 'racer': 2, 'c': 2, 'fx': 2, 'sudden': 2, 'animation': 2, 'vividly': 2, 'tape': 2, 'counting': 2, 'deal': 2, 'allowed': 2, 'judge': 2, 'bore': 2, 'depth': 2, 'dazzling': 2, 'goodness': 2, 'aside': 2, 'substance': 2, 'poorly': 2, 'miss': 2, 'welcome': 2, 'agree': 2, 'trail': 2, 'mysterious': 2, 'scientific': 2, 'explain': 2, 'jennifer': 2, 'enter': 2, 'desire': 2, 'contrast': 2, 'bright': 2, 'astonishing': 2, 'cinematography': 2, 'feast': 2, 'assured': 2, 'political': 2, 'value': 2, 'clumsy': 2, 'critique': 2, 'particular': 2, 'atrocity': 2, 'genuine': 2, 'concern': 2, 'prepared': 2, 'damn': 2, 'hated': 2, 'hanging': 2, 'silver': 2, 'civil': 2, 'jude': 2, 'kidnap': 2, 'renée': 2, 'zellweger': 2, 'calling': 2, 'center': 2, 'confederate': 2, 'north': 2, 'carolina': 2, 'formulaic': 2, 'incidentally': 2, 'farm': 2, 'add': 2, 'ruby': 2, 'cope': 2, 'setting': 2, 'cartoon': 2, 'south': 2, 'winsto

In [61]:
# encode words
reviews_enc = [[word2int[word] for word in review.split()] for review in tqdm(reviews)]

# print first-10 words of first 5 reviews
for i in range(5):
    print(reviews_enc[i][:68])

100%|██████████| 131/131 [00:00<00:00, 65217.07it/s]

[3, 2112, 425, 88, 684, 518, 923, 1304, 76, 426, 1305, 924, 26, 25, 925, 518, 2113, 2114, 9, 133, 234, 76, 316, 30, 1306, 50, 2115, 2116, 2117, 50, 926, 685, 1307, 369, 199, 133, 2118, 235, 116, 316, 276, 518, 2119, 236, 2120, 927, 1308, 686, 2121, 519, 1309, 2122, 134, 2123, 2124, 520, 427, 2125, 370, 277, 2126, 2127, 278, 928, 2128, 134, 135, 2129]
[202, 41, 282, 690, 938, 939, 2147, 940, 65, 1320, 941, 2148, 203, 942, 375, 147, 33, 523, 22, 2149, 432, 2150, 64, 2151, 283, 1321, 173, 10, 2152, 943, 2153, 1322, 2154, 2155, 2156, 22, 204, 88, 376, 524, 2157, 147, 1323, 282, 3, 77, 944, 148, 23, 942, 16, 104, 135, 41, 25, 1324, 935, 137, 116, 2158, 525, 938, 2159, 691, 2160, 91, 2161, 1325]
[86, 202, 24, 945, 20, 11, 433, 2169, 2170, 694, 695, 2171, 696, 88, 2172, 148, 29, 1327, 284, 1328, 13, 2173, 6, 22, 2174, 2175, 434, 239, 103, 377, 697, 698, 82, 285, 2176, 2177, 86, 1329, 2178, 1330, 42, 946, 526, 527, 34, 83, 2179, 2180, 699, 700, 3, 286, 148, 38, 1315, 37, 2181, 92, 19, 2182, 1331, 1332, 1333, 701, 1334, 947, 2183, 76]
[528, 119, 149, 41, 321, 702, 47, 119, 157, 1335, 436, 529, 2193, 1, 2194, 703, 1336, 949, 702, 530, 281, 1337, 374, 157, 26, 531, 53, 14, 2, 120, 1338, 287, 378, 378, 1, 704, 436, 2195, 2196, 4, 121, 23, 702, 1335, 288, 532, 2, 1339, 10, 2197, 205, 1, 240, 237, 378, 1340, 287, 2198, 150, 22, 322, 436, 2199, 533, 206, 702, 2200]
[45, 139, 66, 20, 11, 323, 2201, 950, 2, 61, 207, 139, 534, 83, 1341, 951, 241, 952, 1, 158, 953, 83, 323, 242, 159, 32, 160, 705, 1342, 2202, 2203, 2204, 91, 208, 67, 2205, 209, 706, 20, 11, 93, 535, 160, 13, 161, 2206, 3, 954, 3, 24, 84, 324, 325, 3, 158, 39, 437, 82, 1343, 2207, 2, 1344, 2208, 51, 210, 10, 32, 707]

In [62]:
print(len(reviews_enc))
print(len(reviews_enc[3]))
print(word2int['<PAD>'])

131
67
0

In [63]:
# padding sequences

def pad_features(reviews, pad_id, seq_length=128):
    # features = np.zeros((len(reviews), seq_length), dtype=int)
    features = np.full((len(reviews), seq_length), pad_id, dtype=int)      #Return a new array of given shape (len(reviews), seq_length) and type = int, filled with pad_id.

    for i, row in enumerate(reviews):
        # if seq_length < len(row) then review will be trimmed
        features[i, :len(row)] = np.array(row)[:seq_length]

    return features

seq_length = 256
features = pad_features(reviews_enc, pad_id=word2int['<PAD>'], seq_length=seq_length)       # creating array len 256 filled zero up and then it records real values
                                                                                            # if len < 256 there will be zero 

assert len(features) == len(reviews_enc)                                                    # check count of reviews (true or false)
assert len(features[0]) == seq_length                                                       # check count of  words in review [0] (true or false)

features[:10, :70]

array([[   3, 2112,  425,   88,  684,  518,  923, 1304,   76,  426, 1305,
         924,   26,   25,  925,  518, 2113, 2114,    9,  133,  234,   76,
         316,   30, 1306,   50, 2115, 2116, 2117,   50,  926,  685, 1307,
         369,  199,  133, 2118,  235,  116,  316,  276,  518, 2119,  236,
        2120,  927, 1308,  686, 2121,  519, 1309, 2122,  134, 2123, 2124,
         520,  427, 2125,  370,  277, 2126, 2127,  278,  928, 2128,  134,
         135, 2129, 1310,  687],
       [ 202,   41,  282,  690,  938,  939, 2147,  940,   65, 1320,  941,
        2148,  203,  942,  375,  147,   33,  523,   22, 2149,  432, 2150,
          64, 2151,  283, 1321,  173,   10, 2152,  943, 2153, 1322, 2154,
        2155, 2156,   22,  204,   88,  376,  524, 2157,  147, 1323,  282,
           3,   77,  944,  148,   23,  942,   16,  104,  135,   41,   25,
        1324,  935,  137,  116, 2158,  525,  938, 2159,  691, 2160,   91,
        2161, 1325,  692,    9],
       [  86,  202,   24,  945,   20,   11,  433, 2169, 2170,  694,  695,
        2171,  696,   88, 2172,  148,   29, 1327,  284, 1328,   13, 2173,
           6,   22, 2174, 2175,  434,  239,  103,  377,  697,  698,   82,
         285, 2176, 2177,   86, 1329, 2178, 1330,   42,  946,  526,  527,
          34,   83, 2179, 2180,  699,  700,    3,  286,  148,   38, 1315,
          37, 2181,   92,   19, 2182, 1331, 1332, 1333,  701, 1334,  947,
        2183,   76,  435, 2184],
       [ 528,  119,  149,   41,  321,  702,   47,  119,  157, 1335,  436,
         529, 2193,    1, 2194,  703, 1336,  949,  702,  530,  281, 1337,
         374,  157,   26,  531,   53,   14,    2,  120, 1338,  287,  378,
         378,    1,  704,  436, 2195, 2196,    4,  121,   23,  702, 1335,
         288,  532,    2, 1339,   10, 2197,  205,    1,  240,  237,  378,
        1340,  287, 2198,  150,   22,  322,  436, 2199,  533,  206,  702,
        2200,    0,    0,    0],
       [  45,  139,   66,   20,   11,  323, 2201,  950,    2,   61,  207,
         139,  534,   83, 1341,  951,  241,  952,    1,  158,  953,   83,
         323,  242,  159,   32,  160,  705, 1342, 2202, 2203, 2204,   91,
         208,   67, 2205,  209,  706,   20,   11,   93,  535,  160,   13,
         161, 2206,    3,  954,    3,   24,   84,  324,  325,    3,  158,
          39,  437,   82, 1343, 2207,    2, 1344, 2208,   51,  210,   10,
          32,  707,  122,  707],
       [ 175, 1347,  537,    1,    5, 2223, 1348, 2224, 2225,  327, 2226,
         291,   19,    8,   55,  328,   27,  957,   95,  130,  712,   38,
         538,  713,   78,  438, 1349,   11,   45,  958,    3,  173,  439,
          96, 2227,  107, 2228,   37,    4,  243, 1350,  176,   14,  244,
          61,  163,  329, 1351,  714,  715,  122, 2229,  379, 2230,  539,
         959,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [ 108,   12,    4,   10, 2231,  440, 1352,  292, 1353,  293,   12,
         211,   71,  107, 1354, 2232, 2233,  140,  294,  441, 1352, 2234,
         442,  138, 2235, 1355, 2236,   93, 1356, 2237,  109,  295,  960,
         441,   12,   68,  122,  380,  381,   24, 1357, 2238,    4,  382,
          34, 2239,  441,   34,    1, 2240,   24,  212,   92,   64,  716,
         540, 2241,  177,  245, 1358,   82, 1356, 2242,   12,  150,  141,
          12,  142, 2243,  717],
       [  50,  718,  961, 1360,   97,  541,   26, 2244,   26, 2245, 1361,
          38,  542,   25, 1362, 1363,   50,   16,   98, 1364, 1365, 1366,
         719,  720,   20,   11,  293,  173, 1367,   89,   50, 2246,  296,
        1368,   21,   78,  213,   21, 2247,  383, 2248, 2249,   50,  175,
         429,   42,  695,   44,  110,  212,  962, 2250,  143,   94,   31,
        1369,  721, 2251,  963,    3, 2252,  964,   10,  965, 2253, 2254,
         443,  120,   65,  285],
       [1371,  967,  968,    2,  178,  722,   88,    2,   21,  723,   92,
          27, 2255,    2,  173,    3,   73,  246,  213,  138,   24,  943,
         969,  724,   40,  384,    2,  385,  543,  444, 2256,  179,  445,
        2257,   95,    2,   51,  544,  371,  291, 2258,  970,  446,   10,
          36,  971,    2,   25, 2259,  725, 2260, 2261, 1372,   89,   46,
          78,   62,  158,  151,  144,  726,    3, 1372, 2262,    0,    0,
           0,    0,    0,    0],
       [   4,  143,  972, 2263, 2264,    4,    1,   43,   55,   66,    1,
         545,    6,  973,  386,   77, 1373,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]])

In [64]:
print(features.shape)

(131, 256)

In [65]:
# get labels as numpy
labels = df_new.label.to_numpy()
labels

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1],
      dtype=int64)

In [66]:
# train test splitting
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.0005, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(130, 256)
(1, 256)
(130,)
(1,)

In [ ]:
# define batch size
batch_size = 128

data_train_x = torch.from_numpy(x_train)                            # array to tensor
data_train_y = torch.from_numpy(y_train)
data_test_x = torch.from_numpy(x_test)
data_test_y = torch.from_numpy(y_test)

# create tensor datasets
trainset = TensorDataset(data_train_x, data_train_y)
testset = TensorDataset(data_test_x, data_test_y)

# create dataloaders
trainloader = DataLoader(trainset, shuffle=True, batch_size=batch_size)
testloader = DataLoader(testset, shuffle=True, batch_size=batch_size)

In [70]:
print(data_train_x.shape)
print(data_train_y.shape)
print(data_test_x.shape)
print(data_test_y.shape)

torch.Size([130, 256])
torch.Size([130])
torch.Size([1, 256])
torch.Size([1])