In [1]:
""" This notebook used for creating dataset. """

import torch
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from torchtext.vocab import vocab  
from tqdm import tqdm                                   # progressbar
tqdm.pandas() 
import warnings
warnings.filterwarnings('ignore', category=UserWarning)
from def_preprocessing import preprocessing                 # for def of preprocessing
from collections import Counter, OrderedDict                # for definition of unique words (tokens) in dataframe

c:\Users\Admin\WORK\Project_CV\Model_NLP_sentiment\NLP_sent_venv\lib\site-packages\torchtext\vocab\__init__.py:4: UserWarning:
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
c:\Users\Admin\WORK\Project_CV\Model_NLP_sentiment\NLP_sent_venv\lib\site-packages\torchtext\utils.py:4: UserWarning:
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)

In [2]:
df = pd.read_csv(r'C:\Users\Admin\WORK\Project_CV\Model_NLP_sentiment\data\IMDB Dataset.csv')    # insert path to your data

In [3]:
df.head(2)                                                # check dataframe

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [3]:
# transform sentiment  into the number labels
def transform_label(label):
    return 1 if label == 'positive' else 0

df['label'] = df['sentiment'].apply(transform_label)
df.head(2)

                                              review sentiment  label
0  One of the other reviewers has mentioned that ...  positive      1
1  A wonderful little production. <br /><br />The...  positive      1

In [4]:
df_new = df.loc[0:10]

In [5]:
df_new['clean'] = df_new['review'].apply(preprocessing) 
df_new

C:\Users\Admin\AppData\Local\Temp\ipykernel_12800\3814044920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['clean'] = df_new['review'].apply(preprocessing)

,review,sentiment,label,clean
0,One of the other reviewers has mentioned that ...,positive,1,one reviewer mentioned watching 1 oz episode h...
1,A wonderful little production. <br /><br />The...,positive,1,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,1,thought wonderful way spend Tears eye hot summ...
3,Basically there's a family where a little boy ...,negative,0,basically there family little boy jake think t...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,better matter love Tears eye money visually st...
5,"Probably my all-time favorite movie, a story o...",positive,1,probably alltime favorite movie story selfless...
6,I sure would like to see a resurrection of a u...,positive,1,sure would like see resurrection dated shunt s...
7,"This show was an amazing, fresh & innovative i...",negative,0,show amazing fresh innovative idea 70 first ai...
8,Encouraged by the positive comments about this...,negative,0,encouraged positive comment film looking forwa...
9,If you like original gut wrenching laughter yo...,positive,1,like original gut reaching laughter like movie...
10,Phil the Alien is one of those quirky films wh...,negative,0,phil alien one quirky film humour based around...

In [6]:
 #get all processed reviews
reviews = df_new.clean.values
# merge into single variable, separated by whitespaces
words = ' '.join(reviews)
# obtain list of words
words = words.split()

# check our list
words[:10]

['one',
 'reviewer',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly']

In [7]:
print(len(words))

880

In [8]:
# build vocabulary
counter = Counter(words)
vocab = sorted(counter, key=counter.get, reverse=True)
int2word = dict(enumerate(vocab, 1))
int2word[0] = '<PAD>'
word2int = {word: id for id, word in int2word.items()}

In [9]:

print(counter)
print(vocab)
print(int2word)
print(word2int)

Counter({'one': 14, 'film': 13, 'show': 10, 'movie': 10, 'would': 7, 'see': 7, 'first': 6, 'well': 6, 'like': 6, 'watching': 5, 'oz': 5, 'thing': 5, 'way': 5, 'eye': 5, 'violence': 4, 'go': 4, 'never': 4, 'say': 4, 'get': 4, 'truly': 4, 'comedy': 4, 'Tears': 4, 'character': 4, 'jake': 4, 'matter': 4, 'right': 3, 'city': 3, 'prison': 3, 'far': 3, 'forget': 3, 'pretty': 3, 'got': 3, 'may': 3, 'little': 3, 'great': 3, 'every': 3, 'air': 3, 'point': 3, 'still': 3, 'many': 3, 'u': 3, 'year': 3, 'ive': 3, 'parent': 3, 'make': 3, 'must': 3, 'drama': 3, 'better': 3, 'mr': 3, 'seems': 3, 'people': 3, 'different': 3, 'world': 3, 'find': 3, 'cast': 3, 'performance': 3, 'tv': 3, 'believe': 3, 'funny': 3, 'bad': 3, 'original': 3, 'episode': 2, 'exactly': 2, 'struck': 2, 'scene': 2, 'set': 2, 'word': 2, 'use': 2, 'state': 2, 'high': 2, 'home': 2, 'away': 2, 'appeal': 2, 'due': 2, 'wouldnt': 2, 'dare': 2, 'picture': 2, 'around': 2, 'nasty': 2, 'watched': 2, 'guard': 2, 'whole': 2, 'inmate': 2, 'kill': 2, 'become': 2, 'wonderful': 2, 'production': 2, 'technique': 2, 'give': 2, 'realism': 2, 'piece': 2, 'michael': 2, 'editing': 2, 'life': 2, 'really': 2, 'come': 2, 'rather': 2, 'play': 2, 'particularly': 2, 'thought': 2, 'even': 2, '2': 2, 'young': 2, 'interesting': 2, 'there': 2, 'zombie': 2, 'closet': 2, 'thriller': 2, 'similar': 2, '10': 2, 'love': 2, 'money': 2, 'watch': 2, 'human': 2, 'relation': 2, 'success': 2, 'new': 2, 'another': 2, 'next': 2, 'look': 2, 'live': 2, 'best': 2, 'acting': 2, 'good': 2, 'work': 2, 'probably': 2, 'boring': 2, 'old': 2, 'seen': 2, 'time': 2, 'kid': 2, 'shunt': 2, 'today': 2, 'sea': 2, 'let': 2, 'almost': 2, 'awful': 2, 'titel': 2, 'address': 2, 'reviewer': 1, 'mentioned': 1, '1': 1, 'hooked': 1, 'happened': 1, 'metre': 1, 'brutality': 1, 'unflinching': 1, 'trust': 1, 'faint': 1, 'hearted': 1, 'timid': 1, 'pull': 1, 'punch': 1, 'regard': 1, 'drug': 1, 'sex': 1, 'hardcore': 1, 'classic': 1, 'called': 1, 'nickname': 1, 'given': 1, 'onward': 1, 'maximum': 1, 'security': 1, 'penitentiary': 1, 'focus': 1, 'mainly': 1, 'emerald': 1, 'experimental': 1, 'section': 1, 'cell': 1, 'glass': 1, 'front': 1, 'face': 1, 'inwards': 1, 'privacy': 1, 'agenda': 1, 'em': 1, 'manyaryans': 1, 'muslim': 1, 'gangster': 1, 'latino': 1, 'christian': 1, 'italian': 1, 'irish': 1, 'moreno': 1, 'scuffle': 1, 'death': 1, 'dodgy': 1, 'dealing': 1, 'shady': 1, 'agreement': 1, 'main': 1, 'fact': 1, 'painted': 1, 'mainstream': 1, 'audience': 1, 'charm': 1, 'romance': 1, 'doesnt': 1, 'mess': 1, 'ever': 1, 'saw': 1, 'surreal': 1, 'couldnt': 1, 'ready': 1, 'developed': 1, 'taste': 1, 'accustomed': 1, 'level': 1, 'graphic': 1, 'injustice': 1, 'crooked': 1, 'sold': 1, 'nickel': 1, 'order': 1, 'mannered': 1, 'middle': 1, 'class': 1, 'turned': 1, 'pitch': 1, 'lack': 1, 'street': 1, 'skill': 1, 'experience': 1, 'comfortable': 1, 'uncomfortable': 1, 'viewingthats': 1, 'touch': 1, 'darker': 1, 'side': 1, 'filming': 1, 'assuming': 1, 'oldtimebbc': 1, 'fashion': 1, 'conforming': 1, 'sometimes': 1, 'discomforting': 1, 'sense': 1, 'entire': 1, 'actor': 1, 'extremely': 1, 'chosen': 1, 'sheen': 1, 'polar': 1, 'voice': 1, 'pat': 1, 'seamless': 1, 'guided': 1, 'reference': 1, 'williams': 1, 'diary': 1, 'entry': 1, 'worth': 1, 'terrific': 1, 'written': 1, 'performed': 1, 'masterful': 1, 'master': 1, 'fantasy': 1, 'traditional': 1, 'dream': 1, 'remains': 1, 'solid': 1, 'disappears': 1, 'knowledge': 1, 'sens': 1, 'concerning': 1, 'rton': 1, 'halliwell': 1, 'flat': 1, 'halliwells': 1, 'mural': 1, 'decorating': 1, 'surface': 1, 'terribly': 1, 'done': 1, 'spend': 1, 'hot': 1, 'summer': 1, 'weekend': 1, 'sitting': 1, 'conditioned': 1, 'theater': 1, 'lighthearted': 1, 'plot': 1, 'simplistic': 1, 'dialogue': 1, 'witty': 1, 'liable': 1, 'bread': 1, 'suspected': 1, 'serial': 1, 'killer': 1, 'disappointed': 1, 'realize': 1, 'match': 1, 'risk': 1, 'addiction': 1, 'proof': 1, 'woody': 1, 'allen': 1, 'fully': 1, 'control': 1, 'style': 1, 'grown': 1, 'lovethis': 1, 'id': 1, 'laughed': 1, 'wood': 1, 'decade': 1, 'impressed': 1, 'scarlet': 1, 'johnson': 1, 'managed': 1, 'tone': 1, 'sexy': 1, 'image': 1, 'jumped': 1, 'average': 1, 'spirited': 1, 'womanthis': 1, 'crown': 1, 'jewel': 1, 'career': 1, 'winter': 1, 'devil': 1, 'wear': 1, 'rada': 1, 'superman': 1, 'friend': 1, 'basically': 1, 'family': 1, 'boy': 1, 'think': 1, 'fighting': 1, 'timethis': 1, 'slower': 1, 'soap': 1, 'opera': 1, 'suddenly': 1, 'decides': 1, 'ramo': 1, 'youre': 1, 'going': 1, 'decide': 1, 'watchable': 1, 'divorcing': 1, 'arguing': 1, 'real': 1, 'totally': 1, 'ruin': 1, 'expected': 1, 'boogeyman': 1, 'instead': 1, 'meaningless': 1, 'spots3': 1, 'playing': 1, 'descent': 1, 'dialog': 1, 'shot': 1, 'ignore': 1, 'visually': 1, 'stunning': 1, 'offer': 1, 'vivid': 1, 'portrait': 1, 'telling': 1, 'power': 1, 'situation': 1, 'encounter': 1, 'variation': 1, 'arthur': 1, 'schnitzlers': 1, 'theme': 1, 'director': 1, 'transfer': 1, 'action': 1, 'present': 1, 'york': 1, 'meet': 1, 'connect': 1, 'connected': 1, 'person': 1, 'know': 1, 'previous': 1, 'contact': 1, 'stylish': 1, 'sophisticated': 1, 'luxurious': 1, 'taken': 1, 'habitatthe': 1, 'soul': 1, 'stage': 1, 'loneliness': 1, 'inhabits': 1, 'big': 1, 'place': 1, 'sincere': 1, 'fulfillment': 1, 'discern': 1, 'case': 1, 'encounterthe': 1, 'direction': 1, 'steve': 1, 'buscemi': 1, 'rosario': 1, 'dawson': 1, 'carol': 1, 'kane': 1, 'imperial': 1, 'adrian': 1, 'greater': 1, 'rest': 1, 'talented': 1, 'alive': 1, 'wish': 1, 'luck': 1, 'await': 1, 'anxious': 1, 'alltime': 1, 'favorite': 1, 'story': 1, 'selflessness': 1, 'sacrifice': 1, 'dedication': 1, 'noble': 1, 'cause': 1, 'preach': 1, 'despite': 1, '15': 1, 'last': 1, '25': 1, 'paul': 1, 'lucas': 1, 'brings': 1, 'tear': 1, 'davis': 1, 'sympathetic': 1, 'role': 1, 'delight': 1, 'grand': 1, 'dressed': 1, 'widget': 1, 'child': 1, 'fun': 1, 'mother': 1, 'slow': 1, 'awakening': 1, 'whats': 1, 'happening': 1, 'roof': 1, 'believable': 1, 'startling': 1, 'dozen': 1, 'thumb': 1, 'sure': 1, 'resurrection': 1, 'dated': 1, 'series': 1, 'tech': 1, 'bring': 1, 'back': 1, 'excitement': 1, 'mei': 1, 'grew': 1, 'black': 1, 'white': 1, 'gunsmoke': 1, 'hero': 1, 'weekyou': 1, 'vote': 1, 'comeback': 1, 'hunt': 1, 'need': 1, 'change': 1, 'pace': 1, 'water': 1, 'adventure': 1, 'thank': 1, 'outlet': 1, 'view': 1, 'viewpoint': 1, 'ole': 1, 'wan': 1, 'na': 1, 'saywould': 1, 'nice': 1, 'read': 1, 'plus': 1, 'rhyme': 1, 'line': 1, 'submit': 1, 'leave': 1, 'doubt': 1, 'quite': 1, 'amazing': 1, 'fresh': 1, 'innovative': 1, 'idea': 1, '70': 1, 'aired': 1, '7': 1, '8': 1, 'brilliant': 1, 'dropped': 1, '1990': 1, 'anymore': 1, 'continued': 1, 'decline': 1, 'complete': 1, 'waste': 1, 'disgraceful': 1, 'fallen': 1, 'writing': 1, 'painfully': 1, 'mildly': 1, 'entertaining': 1, 'respite': 1, 'guesthosts': 1, 'hard': 1, 'creator': 1, 'handselected': 1, 'also': 1, 'chose': 1, 'band': 1, 'hack': 1, 'followed': 1, 'recognize': 1, 'brilliance': 1, 'fit': 1, 'replace': 1, 'mediocrity': 1, 'felt': 1, 'star': 1, 'respect': 1, 'made': 1, 'huge': 1, 'cant': 1, 'encouraged': 1, 'positive': 1, 'comment': 1, 'looking': 1, 'forward': 1, 'mistake': 1, '950': 1, 'worst': 1, 'pacing': 1, 'storyline': 1, 'soundtrack': 1, 'song': 1, 'lame': 1, 'country': 1, 'tune': 1, 'played': 1, 'less': 1, 'four': 1, 'cheap': 1, 'extreme': 1, 'rarely': 1, 'happy': 1, 'end': 1, 'credit': 1, 'prevents': 1, 'giving': 1, '1score': 1, 'harvey': 1, 'least': 1, 'making': 1, 'bit': 1, 'effort': 1, 'obsessive': 1, 'gut': 1, 'reaching': 1, 'laughter': 1, 'hell': 1, 'mom': 1, 'liked': 1, 'camp': 1, 'phil': 1, 'alien': 1, 'quirky': 1, 'humour': 1, 'based': 1, 'everything': 1, 'actual': 1, 'punchlinesat': 1, 'odd': 1, 'progressed': 1, 'didnt': 1, 'joke': 1, 'anymoreits': 1, 'low': 1, 'budget': 1, 'thats': 1, 'problem': 1, 'eventually': 1, 'lost': 1, 'interest': 1, 'imagine': 1, 'stone': 1, 'currently': 1, 'partakingfor': 1, 'something': 1, 'try': 1, 'brother': 1, 'planet': 1})
['one', 'film', 'show', 'movie', 'would', 'see', 'first', 'well', 'like', 'watching', 'oz', 'thing', 'way', 'eye', 'violence', 'go', 'never', 'say', 'get', 'truly', 'comedy', 'Tears', 'character', 'jake', 'matter', 'right', 'city', 'prison', 'far', 'forget', 'pretty', 'got', 'may', 'little', 'great', 'every', 'air', 'point', 'still', 'many', 'u', 'year', 'ive', 'parent', 'make', 'must', 'drama', 'better', 'mr', 'seems', 'people', 'different', 'world', 'find', 'cast', 'performance', 'tv', 'believe', 'funny', 'bad', 'original', 'episode', 'exactly', 'struck', 'scene', 'set', 'word', 'use', 'state', 'high', 'home', 'away', 'appeal', 'due', 'wouldnt', 'dare', 'picture', 'around', 'nasty', 'watched', 'guard', 'whole', 'inmate', 'kill', 'become', 'wonderful', 'production', 'technique', 'give', 'realism', 'piece', 'michael', 'editing', 'life', 'really', 'come', 'rather', 'play', 'particularly', 'thought', 'even', '2', 'young', 'interesting', 'there', 'zombie', 'closet', 'thriller', 'similar', '10', 'love', 'money', 'watch', 'human', 'relation', 'success', 'new', 'another', 'next', 'look', 'live', 'best', 'acting', 'good', 'work', 'probably', 'boring', 'old', 'seen', 'time', 'kid', 'shunt', 'today', 'sea', 'let', 'almost', 'awful', 'titel', 'address', 'reviewer', 'mentioned', '1', 'hooked', 'happened', 'metre', 'brutality', 'unflinching', 'trust', 'faint', 'hearted', 'timid', 'pull', 'punch', 'regard', 'drug', 'sex', 'hardcore', 'classic', 'called', 'nickname', 'given', 'onward', 'maximum', 'security', 'penitentiary', 'focus', 'mainly', 'emerald', 'experimental', 'section', 'cell', 'glass', 'front', 'face', 'inwards', 'privacy', 'agenda', 'em', 'manyaryans', 'muslim', 'gangster', 'latino', 'christian', 'italian', 'irish', 'moreno', 'scuffle', 'death', 'dodgy', 'dealing', 'shady', 'agreement', 'main', 'fact', 'painted', 'mainstream', 'audience', 'charm', 'romance', 'doesnt', 'mess', 'ever', 'saw', 'surreal', 'couldnt', 'ready', 'developed', 'taste', 'accustomed', 'level', 'graphic', 'injustice', 'crooked', 'sold', 'nickel', 'order', 'mannered', 'middle', 'class', 'turned', 'pitch', 'lack', 'street', 'skill', 'experience', 'comfortable', 'uncomfortable', 'viewingthats', 'touch', 'darker', 'side', 'filming', 'assuming', 'oldtimebbc', 'fashion', 'conforming', 'sometimes', 'discomforting', 'sense', 'entire', 'actor', 'extremely', 'chosen', 'sheen', 'polar', 'voice', 'pat', 'seamless', 'guided', 'reference', 'williams', 'diary', 'entry', 'worth', 'terrific', 'written', 'performed', 'masterful', 'master', 'fantasy', 'traditional', 'dream', 'remains', 'solid', 'disappears', 'knowledge', 'sens', 'concerning', 'rton', 'halliwell', 'flat', 'halliwells', 'mural', 'decorating', 'surface', 'terribly', 'done', 'spend', 'hot', 'summer', 'weekend', 'sitting', 'conditioned', 'theater', 'lighthearted', 'plot', 'simplistic', 'dialogue', 'witty', 'liable', 'bread', 'suspected', 'serial', 'killer', 'disappointed', 'realize', 'match', 'risk', 'addiction', 'proof', 'woody', 'allen', 'fully', 'control', 'style', 'grown', 'lovethis', 'id', 'laughed', 'wood', 'decade', 'impressed', 'scarlet', 'johnson', 'managed', 'tone', 'sexy', 'image', 'jumped', 'average', 'spirited', 'womanthis', 'crown', 'jewel', 'career', 'winter', 'devil', 'wear', 'rada', 'superman', 'friend', 'basically', 'family', 'boy', 'think', 'fighting', 'timethis', 'slower', 'soap', 'opera', 'suddenly', 'decides', 'ramo', 'youre', 'going', 'decide', 'watchable', 'divorcing', 'arguing', 'real', 'totally', 'ruin', 'expected', 'boogeyman', 'instead', 'meaningless', 'spots3', 'playing', 'descent', 'dialog', 'shot', 'ignore', 'visually', 'stunning', 'offer', 'vivid', 'portrait', 'telling', 'power', 'situation', 'encounter', 'variation', 'arthur', 'schnitzlers', 'theme', 'director', 'transfer', 'action', 'present', 'york', 'meet', 'connect', 'connected', 'person', 'know', 'previous', 'contact', 'stylish', 'sophisticated', 'luxurious', 'taken', 'habitatthe', 'soul', 'stage', 'loneliness', 'inhabits', 'big', 'place', 'sincere', 'fulfillment', 'discern', 'case', 'encounterthe', 'direction', 'steve', 'buscemi', 'rosario', 'dawson', 'carol', 'kane', 'imperial', 'adrian', 'greater', 'rest', 'talented', 'alive', 'wish', 'luck', 'await', 'anxious', 'alltime', 'favorite', 'story', 'selflessness', 'sacrifice', 'dedication', 'noble', 'cause', 'preach', 'despite', '15', 'last', '25', 'paul', 'lucas', 'brings', 'tear', 'davis', 'sympathetic', 'role', 'delight', 'grand', 'dressed', 'widget', 'child', 'fun', 'mother', 'slow', 'awakening', 'whats', 'happening', 'roof', 'believable', 'startling', 'dozen', 'thumb', 'sure', 'resurrection', 'dated', 'series', 'tech', 'bring', 'back', 'excitement', 'mei', 'grew', 'black', 'white', 'gunsmoke', 'hero', 'weekyou', 'vote', 'comeback', 'hunt', 'need', 'change', 'pace', 'water', 'adventure', 'thank', 'outlet', 'view', 'viewpoint', 'ole', 'wan', 'na', 'saywould', 'nice', 'read', 'plus', 'rhyme', 'line', 'submit', 'leave', 'doubt', 'quite', 'amazing', 'fresh', 'innovative', 'idea', '70', 'aired', '7', '8', 'brilliant', 'dropped', '1990', 'anymore', 'continued', 'decline', 'complete', 'waste', 'disgraceful', 'fallen', 'writing', 'painfully', 'mildly', 'entertaining', 'respite', 'guesthosts', 'hard', 'creator', 'handselected', 'also', 'chose', 'band', 'hack', 'followed', 'recognize', 'brilliance', 'fit', 'replace', 'mediocrity', 'felt', 'star', 'respect', 'made', 'huge', 'cant', 'encouraged', 'positive', 'comment', 'looking', 'forward', 'mistake', '950', 'worst', 'pacing', 'storyline', 'soundtrack', 'song', 'lame', 'country', 'tune', 'played', 'less', 'four', 'cheap', 'extreme', 'rarely', 'happy', 'end', 'credit', 'prevents', 'giving', '1score', 'harvey', 'least', 'making', 'bit', 'effort', 'obsessive', 'gut', 'reaching', 'laughter', 'hell', 'mom', 'liked', 'camp', 'phil', 'alien', 'quirky', 'humour', 'based', 'everything', 'actual', 'punchlinesat', 'odd', 'progressed', 'didnt', 'joke', 'anymoreits', 'low', 'budget', 'thats', 'problem', 'eventually', 'lost', 'interest', 'imagine', 'stone', 'currently', 'partakingfor', 'something', 'try', 'brother', 'planet']

In [10]:
# encode words
reviews_enc = [[word2int[word] for word in review.split()] for review in tqdm(reviews)]

# print first-10 words of first 5 reviews
for i in range(5):
    print(reviews_enc[i][:68])

100%|██████████| 11/11 [00:00<00:00, 7305.99it/s]

[1, 140, 141, 10, 142, 11, 62, 143, 26, 63, 144, 145, 7, 12, 64, 11, 146, 147, 65, 15, 66, 26, 67, 16, 148, 3, 149, 150, 151, 3, 152, 153, 154, 155, 156, 15, 157, 158, 68, 67, 159, 11, 160, 161, 162, 163, 164, 69, 165, 166, 167, 168, 27, 169, 170, 28, 171, 172, 173, 174, 175, 176, 70, 177, 178, 27, 71, 179]
[86, 34, 87, 232, 88, 233, 234, 235, 89, 236, 237, 238, 239, 90, 240, 91, 241, 242, 8, 243, 92, 244, 32, 245, 246, 247, 20, 6, 248, 93, 249, 250, 251, 252, 253, 8, 254, 10, 255, 256, 257, 91, 258, 87, 1, 35, 259, 21, 94, 90, 95, 96, 71, 34, 12, 260, 81, 97, 68, 261, 262, 88, 263, 264, 265, 98, 266, 267]
[100, 86, 13, 278, 22, 14, 279, 280, 281, 282, 37, 283, 284, 10, 285, 21, 286, 287, 288, 289, 23, 290, 101, 8, 291, 292, 293, 294, 33, 295, 296, 297, 38, 102, 298, 299, 100, 300, 301, 302, 39, 303, 304, 305, 40, 41, 306, 307, 308, 309, 1, 310, 21, 42, 76, 18, 311, 43, 17, 312, 313, 314, 315, 316, 317, 318, 319, 26]
[332, 105, 333, 34, 334, 24, 335, 105, 106, 107, 44, 336, 337, 4, 338, 339, 340, 341, 24, 342, 85, 343, 84, 106, 7, 344, 345, 45, 2, 46, 346, 108, 47, 47, 4, 347, 44, 348, 349, 9, 350, 94, 24, 107, 351, 352, 2, 353, 6, 354, 109, 4, 355, 80, 47, 356, 108, 357, 110, 8, 358, 44, 359, 360, 361, 24, 362]
[48, 25, 111, 22, 14, 112, 363, 364, 2, 113, 49, 25, 365, 41, 366, 367, 114, 115, 4, 50, 368, 41, 112, 369, 116, 51, 52, 370, 371, 372, 373, 374, 98, 375, 376, 377, 378, 379, 22, 14, 117, 380, 52, 23, 381, 382, 1, 383, 1, 13, 118, 119, 384, 1, 50, 385, 386, 38, 387, 388, 2, 389, 390, 120, 391, 6, 51, 121]

In [11]:
print(len(reviews_enc))
print(len(reviews_enc[3]))
print(word2int['<PAD>'])

11
67
0

In [12]:
# padding sequences

def pad_features(reviews, pad_id, seq_length=128):
    # features = np.zeros((len(reviews), seq_length), dtype=int)
    features = np.full((len(reviews), seq_length), pad_id, dtype=int)      #Return a new array of given shape (len(reviews), seq_length) and type = int, filled with pad_id.

    for i, row in enumerate(reviews):
        # if seq_length < len(row) then review will be trimmed
        features[i, :len(row)] = np.array(row)[:seq_length]

    return features

seq_length = 256
features = pad_features(reviews_enc, pad_id=word2int['<PAD>'], seq_length=seq_length)       # creating array len 256 filled zero up and then it records real values
                                                                                            # if len < 256 there will be zero 

assert len(features) == len(reviews_enc)                                                    # check count of reviews (true or false)
assert len(features[0]) == seq_length                                                       # check count of  words in review [0] (true or false)

features[:10, :70]

array([[  1, 140, 141,  10, 142,  11,  62, 143,  26,  63, 144, 145,   7,
         12,  64,  11, 146, 147,  65,  15,  66,  26,  67,  16, 148,   3,
        149, 150, 151,   3, 152, 153, 154, 155, 156,  15, 157, 158,  68,
         67, 159,  11, 160, 161, 162, 163, 164,  69, 165, 166, 167, 168,
         27, 169, 170,  28, 171, 172, 173, 174, 175, 176,  70, 177, 178,
         27,  71, 179, 180, 181],
       [ 86,  34,  87, 232,  88, 233, 234, 235,  89, 236, 237, 238, 239,
         90, 240,  91, 241, 242,   8, 243,  92, 244,  32, 245, 246, 247,
         20,   6, 248,  93, 249, 250, 251, 252, 253,   8, 254,  10, 255,
        256, 257,  91, 258,  87,   1,  35, 259,  21,  94,  90,  95,  96,
         71,  34,  12, 260,  81,  97,  68, 261, 262,  88, 263, 264, 265,
         98, 266, 267,  99,  65],
       [100,  86,  13, 278,  22,  14, 279, 280, 281, 282,  37, 283, 284,
         10, 285,  21, 286, 287, 288, 289,  23, 290, 101,   8, 291, 292,
        293, 294,  33, 295, 296, 297,  38, 102, 298, 299, 100, 300, 301,
        302,  39, 303, 304, 305,  40,  41, 306, 307, 308, 309,   1, 310,
         21,  42,  76,  18, 311,  43,  17, 312, 313, 314, 315, 316, 317,
        318, 319,  26, 320, 321],
       [332, 105, 333,  34, 334,  24, 335, 105, 106, 107,  44, 336, 337,
          4, 338, 339, 340, 341,  24, 342,  85, 343,  84, 106,   7, 344,
        345,  45,   2,  46, 346, 108,  47,  47,   4, 347,  44, 348, 349,
          9, 350,  94,  24, 107, 351, 352,   2, 353,   6, 354, 109,   4,
        355,  80,  47, 356, 108, 357, 110,   8, 358,  44, 359, 360, 361,
         24, 362,   0,   0,   0],
       [ 48,  25, 111,  22,  14, 112, 363, 364,   2, 113,  49,  25, 365,
         41, 366, 367, 114, 115,   4,  50, 368,  41, 112, 369, 116,  51,
         52, 370, 371, 372, 373, 374,  98, 375, 376, 377, 378, 379,  22,
         14, 117, 380,  52,  23, 381, 382,   1, 383,   1,  13, 118, 119,
        384,   1,  50, 385, 386,  38, 387, 388,   2, 389, 390, 120, 391,
          6,  51, 121,  53, 121],
       [126, 421, 422,   4, 423, 424, 425, 426, 427, 428, 429, 127,  17,
         19, 128, 430, 129, 431, 130, 432, 433,  42, 434, 435,  56, 436,
        437,  14,  48, 438,   1,  20, 439, 440, 441, 131, 442,  18,   9,
        443, 444, 445,  45, 446, 113, 447, 448, 449, 450, 451,  53, 452,
        453, 454, 455, 456,   4,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0],
       [457,   5,   9,   6, 458, 459, 132, 460, 461, 133,   5, 462, 463,
        131, 464, 465, 466, 467, 468,  57, 132, 469, 470,  36, 471, 472,
        473, 117, 134, 474, 475, 476, 477,  57,   5, 125,  53, 478, 479,
         13, 480, 481,   9, 482,  40, 483,  57,  40,   4, 484,  13,  58,
         43,  32, 485, 486, 487, 488, 489, 490,  38, 134, 491,   5, 110,
        492,   5, 135, 493, 494],
       [  3, 497, 498, 499, 500, 501,   7, 502,   7, 503, 504,  42, 505,
         12, 506, 507,   3,  95,  59, 508, 509, 510, 511, 512,  22,  14,
        133,  20, 513,  29,   3, 514, 515, 516,  60,  56, 136,  60, 517,
        518, 519, 520,   3, 126,  75,  39,  37,  54, 521,  58, 522, 523,
         61,  55, 524, 525, 526, 527, 528,   1, 529, 530,   6, 531, 532,
        533, 534,  46,  89, 102],
       [540, 541, 542,   2, 543, 544,  10,   2,  60, 545,  43, 129, 546,
          2,  20,   1, 547, 137, 136,  36,  13,  93, 548, 549, 123, 550,
          2, 551, 552, 553, 554, 555, 556, 557, 130,   2, 120, 558,  79,
        127, 559, 560, 561,   6, 562, 563,   2,  12, 564, 565, 566, 567,
        138,  29, 122,  56, 568,  50, 569, 570, 571,   1, 138, 572,   0,
          0,   0,   0,   0,   0],
       [  9,  61, 573, 574, 575,   9,   4, 103, 128, 111,   4, 576, 101,
        577, 578,  35, 579,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0]])

In [13]:
print(features.shape)

(11, 256)

In [14]:
# get labels as numpy
labels = df_new.label.to_numpy()
labels

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [15]:
# train test splitting
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.0005, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 256)
(1, 256)
(10,)
(1,)

In [ ]:
data_train_x = torch.from_numpy(x_train)                            # array to tensor
data_train_y = torch.from_numpy(y_train)
data_test_x = torch.from_numpy(x_test)
data_test_y = torch.from_numpy(y_test)

# create tensor datasets
trainset = TensorDataset(data_train_x, data_train_y)
testset = TensorDataset(data_test_x, data_test_y)

In [17]:
print(data_train_x.shape)
print(data_train_y.shape)
print(data_test_x.shape)
print(data_test_y.shape)

torch.Size([10, 256])
torch.Size([10])
torch.Size([1, 256])
torch.Size([1])